name: Angular CI/CD

on:
  push:
    branches:
      - developement
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - uses: actions/checkout@v3

      # Setup Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install dependencies
      - run: npm ci
        working-directory: HealthCare

      # Build Angular app
      - run: npm run build -- --configuration production
        working-directory: HealthCare

      # Flatten browser folder
      - run: |
          cd HealthCare/dist/health-care
          if [ -d browser ]; then
            mv browser/* .
            rmdir browser
          fi

      # Azure login
      - uses: azure/login@v2
        with:
          creds: |
            {
              "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
              "tenantId": "${{ secrets.AZURE_TENANT_ID }}",
              "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
            }

      # Deploy Angular app
      - uses: azure/webapps-deploy@v3
        with:
          app-name: dev-lis-care-web
          slot-name: production
          package: ./HealthCare/dist/health-care/
