name: Angular CI/CD

on:
  push:
    branches:
      - developement   # Build only for dev branch
      - main           # Build + deploy for main branch
  pull_request:
    branches:
      - main           # Optional: test PRs before merging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install dependencies in HealthCare folder
      - name: Install dependencies
        run: npm ci
        working-directory: HealthCare

      # Build Angular app in HealthCare folder
      - name: Build Angular app
        run: npm run build -- --configuration production
        working-directory: HealthCare

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'  # Deploy only on main branch

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Azure login via Service Principal
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: |
            {
              "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
              "tenantId": "${{ secrets.AZURE_TENANT_ID }}",
              "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
            }

      # Deploy Angular app to Azure Web App
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: dev-lis-care-web
          slot-name: production
          package: ./HealthCare/dist/health-care/browser
