name: Angular CI/CD

on:
  push:
    branches:
      - developement   # build only for dev
      - main           # build + deploy for main
  pull_request:
    branches:
      - developement
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Node.js
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Install dependencies
      - name: Install dependencies
        run: npm ci
        working-directory: HealthCare

      # Build Angular project
      - name: Build Angular app
        run: npm run build -- --configuration production
        working-directory: HealthCare

      # Flatten browser folder
      - name: Flatten browser folder
        run: |
          cd HealthCare/dist/health-care
          if [ -d browser ]; then
            mv browser/* .
            rmdir browser
          fi

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'   # deploy only on main branch

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Azure login using Service Principal
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: |
            {
              "clientId": "${{ secrets.AZURE_CLIENT_ID }}",
              "clientSecret": "${{ secrets.AZURE_CLIENT_SECRET }}",
              "tenantId": "${{ secrets.AZURE_TENANT_ID }}",
              "subscriptionId": "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
            }

      # Deploy Angular app to Azure Web App
      - name: Deploy Angular app to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: dev-lis-care-web
          slot-name: production
          package: ./HealthCare/dist/health-care/
